In [1]:
import numpy as np
mat1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
mat1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
mat1.shape

(4, 3)

In [3]:
mat2 = np.reshape(mat1, [3,4])
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
mat2.shape

(3, 4)

In [5]:
mat3 = np.reshape(mat1, [3,2,2])
mat3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [6]:
mat3.shape

(3, 2, 2)

In [8]:
mat4 = np.reshape(mat1, [12])
mat4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
mat4.shape

(12,)

In [10]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
mat.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [11]:
mat.shape

(4, 3)

In [12]:
mat.T.shape

(3, 4)

In [13]:
np.reshape(mat1, [3,4]) == mat1.T

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])