In [7]:
import numpy as np
vec1 = np.array([1,2,3,4,5,6,7,8,9,10])
vec1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
vec1.shape

(10,)

In [2]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
mat1.shape

(4, 3)

In [3]:
mat2 = np.matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat2

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [13]:
ten1 = np.array([ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]], [[19,20,21],[22,23,24]] ])
ten1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [14]:
ten1.shape

(4, 2, 3)