In [1]:
import numpy as np
mat1 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
mat1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [2]:
mat1.shape

(2, 2, 3)

In [4]:
mat2 = mat1.T
mat2

array([[[1, 1],
        [4, 4]],

       [[2, 2],
        [5, 5]],

       [[3, 3],
        [6, 6]]])

In [5]:
mat2.shape

(3, 2, 2)

In [6]:
mat3 = mat2.dot(mat1)
mat3

array([[[[ 5,  7,  9],
         [ 5,  7,  9]],

        [[20, 28, 36],
         [20, 28, 36]]],


       [[[10, 14, 18],
         [10, 14, 18]],

        [[25, 35, 45],
         [25, 35, 45]]],


       [[[15, 21, 27],
         [15, 21, 27]],

        [[30, 42, 54],
         [30, 42, 54]]]])

In [7]:
mat3.shape

(3, 2, 2, 3)