In [2]:
import numpy as np
mat1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
mat2 = np.array([[2,1,4], [4,1,7], [4,2,9], [5,21,1]])

In [8]:
mat1.shape

(4, 3)

In [9]:
mat2.shape

(4, 3)

In [4]:
mat1.dot(mat2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [5]:
mat1.dot(mat2.T)

array([[ 16,  27,  35,  50],
       [ 37,  63,  80, 131],
       [ 58,  99, 125, 212],
       [ 79, 135, 170, 293]])

In [7]:
mat1.T.dot(mat2)

array([[ 96, 229, 105],
       [111, 254, 126],
       [126, 279, 147]])

In [10]:
np.reshape(mat1, [3,4]).dot(mat2)

array([[ 42,  93,  49],
       [102, 193, 133],
       [162, 293, 217]])